### ISSUE TITLE
Online version unavailable

### ISSUE THREAD

**Issue by gsainsbury86** [YaoChengLab/StomaVision#5]
I went to test the online version of the application at https://stomavision.streamlit.app/ and had an error.

<img width="523" alt="Screenshot 2024-05-08 at 12 04 33 PM" src="https://github.com/YaoChengLab/StomaVision/assets/10837/71d0c18f-37f9-4e7f-bd8d-1f07645dc381">

The "Contact Support" link linked to create an issue at the https://github.com/instill-ai/model-stomata-instance-segmentation-dvc repository, but Issues have been disabled on that page.

**Comment by yalinpsb** [comment]
Thank you for reporting the error. There's a connection issue between Streamlit and our backend  server that hosts the inference model. We're currently working on a fix and apologize for any inconvenience caused.

**Comment by yalinpsb** [comment]
> I went to test the online version of the application at https://stomavision.streamlit.app/ and had an error.
...

Thank you for reporting the error. There's a connection issue between Streamlit and our backend server that hosts the inference model. We're currently working on a fix and apologize for any inconvenience caused.

**Comment by yalinpsb** [comment]
> > I went to test the online version of the application at https://stomavision.streamlit.app/ and had an error.
> > ...

Good news! The Streamlit app is back online now. (Total) Images with size < 32MB should work.

--- More technical details ---
1. We just realized the Python program will batch all uploaded images and send them all at once to Instill Cloud pipeline-backend, and if the total size is larger than 10MB, the app will crash.
2. We’ve also found a bug in our backend service which blocks the user uploading image size larger than 4MB. If the user does so, the current Streamlit app will drop the image and show empty result on the UI.
3. The image size of < 32 Mb is restricted by a 3rd-party dependency which requires a longer time window to fix.
4. Free-tier Streamlit doesn’t offer automatic app restarting, so we will move the demo site to Instill Cloud pipeline playground (where we have the full control of the app and the data flow) ASAP.

**Comment by gsainsbury86** [comment]
Thank you, we'll have a look at how it performs with some of our images!
